[2024-08-14T01:00:41.713+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T01:00:41.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-08-14T00:59:49.835629+00:00 [queued]>
[2024-08-14T01:00:41.982+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-08-14T00:59:49.835629+00:00 [queued]>
[2024-08-14T01:00:41.984+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-14T01:00:42.056+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_municipios> on 2024-08-14 00:59:49.835629+00:00
[2024-08-14T01:00:42.064+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=5851) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T01:00:42.072+0000] {standard_task_runner.py:64} INFO - Started process 5860 to run task
[2024-08-14T01:00:42.075+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_municipios', 'manual__2024-08-14T00:59:49.835629+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpy2jya15q']
[2024-08-14T01:00:42.078+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask get_municipios
[2024-08-14T01:00:42.191+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.get_municipios manual__2024-08-14T00:59:49.835629+00:00 [running]> on host 68978d07c676
[2024-08-14T01:00:42.525+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_municipios' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:59:49.835629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T00:59:49.835629+00:00'
[2024-08-14T01:00:42.539+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T01:00:43.308+0000] {warnings.py:112} WARNING - /opt/***/dags/weather_etl_dag.py:80: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_municipios = pd.read_sql_query(query, conn)

[2024-08-14T01:00:44.869+0000] {logging_mixin.py:188} INFO - Municipios obtenidos:    cve_mun              nom_mun  lat_decimal  lon_decimal
0        1    AMEALCO DE BONFIL    20.186444  -100.144195
1        2      PINAL DE AMOLES    21.135302   -99.627540
2        3          ARROYO SECO    21.548036   -99.689166
3        4  CADEREYTA DE MONTES    20.695023   -99.815633
4        5                COLON    20.788326  -100.045430
[2024-08-14T01:00:45.207+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T01:00:45.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T01:00:45.220+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_municipios, run_id=manual__2024-08-14T00:59:49.835629+00:00, execution_date=20240814T005949, start_date=20240814T010041, end_date=20240814T010045
[2024-08-14T01:00:45.335+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-14T01:00:45.418+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T01:00:45.483+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
