[2024-08-14T00:12:12.856+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T00:12:13.034+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.fetch_weather_data manual__2024-08-14T00:11:24.050492+00:00 [queued]>
[2024-08-14T00:12:13.052+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.fetch_weather_data manual__2024-08-14T00:11:24.050492+00:00 [queued]>
[2024-08-14T00:12:13.116+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-14T00:12:13.234+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2024-08-14 00:11:24.050492+00:00
[2024-08-14T00:12:13.240+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4606) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T00:12:13.242+0000] {standard_task_runner.py:64} INFO - Started process 4608 to run task
[2024-08-14T00:12:13.242+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'fetch_weather_data', 'manual__2024-08-14T00:11:24.050492+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpadxwurt1']
[2024-08-14T00:12:13.245+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask fetch_weather_data
[2024-08-14T00:12:13.347+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.fetch_weather_data manual__2024-08-14T00:11:24.050492+00:00 [running]> on host 68978d07c676
[2024-08-14T00:12:13.587+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:11:24.050492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T00:11:24.050492+00:00'
[2024-08-14T00:12:13.618+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T00:12:31.090+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T00:12:31.091+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T00:12:31.099+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=fetch_weather_data, run_id=manual__2024-08-14T00:11:24.050492+00:00, execution_date=20240814T001124, start_date=20240814T001213, end_date=20240814T001231
[2024-08-14T00:12:31.215+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-14T00:12:31.235+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T00:12:31.388+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
