[2024-09-05T01:00:24.312+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T01:00:24.336+0000] {taskinstance.py:2593} INFO - Dependencies not met for <TaskInstance: weather_etl_dag.fetch_weather_data manual__2024-09-05T00:32:19.554061+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-09-05T01:00:24.336049+00:00 and task will be retried at 2024-09-05T01:04:34.625460+00:00.
[2024-09-05T01:00:24.397+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
