[2024-08-14T00:13:47.754+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T00:13:47.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data manual__2024-08-14T00:11:24.050492+00:00 [queued]>
[2024-08-14T00:13:47.912+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data manual__2024-08-14T00:11:24.050492+00:00 [queued]>
[2024-08-14T00:13:47.913+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-14T00:13:47.982+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_forecast_and_drought_data> on 2024-08-14 00:11:24.050492+00:00
[2024-08-14T00:13:47.988+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4632) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T00:13:47.992+0000] {standard_task_runner.py:64} INFO - Started process 4634 to run task
[2024-08-14T00:13:47.990+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_forecast_and_drought_data', 'manual__2024-08-14T00:11:24.050492+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp2e4lswzs']
[2024-08-14T00:13:47.993+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask get_forecast_and_drought_data
[2024-08-14T00:13:48.062+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.get_forecast_and_drought_data manual__2024-08-14T00:11:24.050492+00:00 [running]> on host 68978d07c676
[2024-08-14T00:13:48.264+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_forecast_and_drought_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:11:24.050492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T00:11:24.050492+00:00'
[2024-08-14T00:13:48.265+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T00:13:48.948+0000] {warnings.py:112} WARNING - /opt/***/dags/weather_etl_dag.py:226: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_pronosticos_clima = pd.read_sql_query(query, conn)

[2024-08-14T00:13:49.095+0000] {warnings.py:112} WARNING - /opt/***/dags/weather_etl_dag.py:230: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sequia = pd.read_sql_query(query, conn)

[2024-08-14T00:13:50.046+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T00:13:50.047+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T00:13:50.057+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_forecast_and_drought_data, run_id=manual__2024-08-14T00:11:24.050492+00:00, execution_date=20240814T001124, start_date=20240814T001347, end_date=20240814T001350
[2024-08-14T00:13:50.142+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-14T00:13:50.153+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
