[2024-09-05T00:39:10.983+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:39:11.026+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data manual__2024-09-05T00:27:08.901871+00:00 [queued]>
[2024-09-05T00:39:11.056+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data manual__2024-09-05T00:27:08.901871+00:00 [queued]>
[2024-09-05T00:39:11.070+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T00:39:11.158+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-09-05 00:27:08.901871+00:00
[2024-09-05T00:39:11.166+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=480) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:39:11.169+0000] {standard_task_runner.py:72} INFO - Started process 482 to run task
[2024-09-05T00:39:11.169+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'manual__2024-09-05T00:27:08.901871+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp5jyo1195']
[2024-09-05T00:39:11.172+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask translate_and_clean_data
[2024-09-05T00:39:11.312+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data manual__2024-09-05T00:27:08.901871+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:39:11.627+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T00:27:08.901871+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-05T00:27:08.901871+00:00'
[2024-09-05T00:39:11.628+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:39:11.642+0000] {logging_mixin.py:190} INFO - Recuperando DataFrame de pronósticos desde XCom
[2024-09-05T00:39:11.685+0000] {logging_mixin.py:190} INFO - Número de registros en pronósticos: 18
[2024-09-05T00:39:11.705+0000] {logging_mixin.py:190} INFO - Pronósticos antes de limpiar y traducir:    cve_mun            municipio  ... wind_kph  humidity
0        1    AMEALCO DE BONFIL  ...     16.9        77
1        2      PINAL DE AMOLES  ...     19.8        77
2        3          ARROYO SECO  ...     19.1        82
3        4  CADEREYTA DE MONTES  ...     16.2        78
4        5                COLON  ...     19.8        77

[5 rows x 10 columns]
[2024-09-05T00:40:10.747+0000] {logging_mixin.py:190} INFO - Pronósticos después de limpiar y traducir:    cve_mun            municipio  ... viento_kph  humedad
0        1    Amealco De Bonfil  ...       16.9       77
1        2      Pinal De Amoles  ...       19.8       77
2        3          Arroyo Seco  ...       19.1       82
3        4  Cadereyta De Montes  ...       16.2       78
4        5                Colon  ...       19.8       77

[5 rows x 10 columns]
[2024-09-05T00:40:10.905+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:40:10.933+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:40:10.934+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=translate_and_clean_data, run_id=manual__2024-09-05T00:27:08.901871+00:00, execution_date=20240905T002708, start_date=20240905T003911, end_date=20240905T004010
[2024-09-05T00:40:11.105+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:40:11.186+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-05T00:40:11.567+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:40:11.671+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
