[2024-08-14T00:20:46.816+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T00:20:47.576+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-08-14T00:19:13.436681+00:00 [queued]>
[2024-08-14T00:20:47.603+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-08-14T00:19:13.436681+00:00 [queued]>
[2024-08-14T00:20:47.679+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-14T00:20:47.769+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_municipios> on 2024-08-14 00:19:13.436681+00:00
[2024-08-14T00:20:49.405+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_municipios', 'manual__2024-08-14T00:19:13.436681+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmphap9a1g9']
[2024-08-14T00:20:49.408+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask get_municipios
[2024-08-14T00:20:49.433+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=5120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T00:20:49.434+0000] {standard_task_runner.py:64} INFO - Started process 5122 to run task
[2024-08-14T00:20:51.258+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.get_municipios manual__2024-08-14T00:19:13.436681+00:00 [running]> on host 68978d07c676
[2024-08-14T00:20:51.727+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_municipios' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:19:13.436681+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T00:19:13.436681+00:00'
[2024-08-14T00:20:51.734+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T00:20:52.424+0000] {warnings.py:112} WARNING - /opt/***/dags/weather_etl_dag.py:80: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_municipios = pd.read_sql_query(query, conn)

[2024-08-14T00:20:52.824+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T00:20:52.833+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T00:20:52.848+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_municipios, run_id=manual__2024-08-14T00:19:13.436681+00:00, execution_date=20240814T001913, start_date=20240814T002047, end_date=20240814T002052
[2024-08-14T00:20:52.992+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-14T00:20:53.015+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T00:20:53.084+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
